export enum Permission {
  USER_READ = "USER_READ",
  USER_CREATE = "USER_CREATE",
  USER_UPDATE = "USER_UPDATE",
  USER_DELETE = "USER_DELETE",

  PROFILE_READ = "PROFILE_READ",
  PROFILE_UPDATE = "PROFILE_UPDATE",

  SESSION_READ = "SESSION_READ",
  SESSION_DELETE = "SESSION_DELETE",

  COURSE_READ = "COURSE_READ",
  COURSE_CREATE = "COURSE_CREATE",
  COURSE_UPDATE = "COURSE_UPDATE",
  COURSE_DELETE = "COURSE_DELETE",
}
