export enum SecurityEvent {
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILED = "LOGIN_FAILED",

  PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED",
  PASSWORD_CHANGED = "PASSWORD_CHANGED",

  EMAIL_VERIFIED = "EMAIL_VERIFIED",

  TOKEN_REFRESHED = "TOKEN_REFRESHED",

  LOGOUT = "LOGOUT",

  LOGOUT_ALL = "LOGOUT_ALL",

  SESSION_REVOKED = "SESSION_REVOKED",

  OTHER_SESSIONS_REVOKED = "OTHER_SESSIONS_REVOKED",

  ACCOUNT_LOCKED = "ACCOUNT_LOCKED",

  SUSPICIOUS_LOGIN = "SUSPICIOUS_LOGIN",
}
