export enum AuditEvent {
  REGISTER = "REGISTER",

  LOGIN = "LOGIN",

  LOGIN_FAILED = "LOGIN_FAILED",

  LOGOUT = "LOGOUT",

  LOGOUT_ALL = "LOGOUT_ALL",

  TOKEN_REFRESH = "TOKEN_REFRESH",

  PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED",

  PASSWORD_RESET = "PASSWORD_RESET",

  EMAIL_VERIFIED = "EMAIL_VERIFIED",

  EMAIL_VERIFICATION_RESENT = "EMAIL_VERIFICATION_RESENT",

  SESSION_REVOKED = "SESSION_REVOKED",

  SESSION_REVOKED_ALL = "SESSION_REVOKED_ALL",

  ACCOUNT_LOCKED = "ACCOUNT_LOCKED",
}
