import { env } from "./env.js";

export const config = {
  env: env.NODE_ENV,
  port: env.PORT,
  JWT_ACCESS_SECRET: env.JWT_ACCESS_SECRET,
  JWT_REFRESH_SECRET: env.JWT_REFRESH_SECRET,
  JWT_ACCESS_EXPIRES_IN: env.JWT_ACCESS_EXPIRES_IN,
  JWT_REFRESH_EXPIRES_IN: env.JWT_REFRESH_EXPIRES_IN,
  MONGODB_URI: env.MONGODB_URI,
  SESSION_EXPIRES_IN_DAYS: env.SESSION_EXPIRES_IN_DAYS,
  RESEND_API_KEY: env.RESEND_API_KEY,
  EMAIL_FROM: env.EMAIL_FROM,
} as const;
